version: '3.8'
services:
  frontend:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - grpc_service
    networks:
      - app-network
  grpc_service:
    build: ./gRPC
    ports:
      - "50051:50051"
    depends_on:
      - db
    networks:
      - app-network
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_NAME: test
        DB_USER: postgres
        DB_PASSWORD: password

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge