# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07service\"\x07\n\x05\x45mpty\"$\n\x08\x44\x61taItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t\"/\n\x0c\x44\x61taResponse\x12\x1f\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x11.service.DataItem2C\n\x0f\x44\x61tabaseService\x12\x30\n\x07GetData\x12\x0e.service.Empty\x1a\x15.service.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_DATAITEM']._serialized_start=35
  _globals['_DATAITEM']._serialized_end=71
  _globals['_DATARESPONSE']._serialized_start=73
  _globals['_DATARESPONSE']._serialized_end=120
  _globals['_DATABASESERVICE']._serialized_start=122
  _globals['_DATABASESERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
